# -*- coding: utf-8 -*-
"""bitopro_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yWj8CWALPMu1lfQAUaEEOBBiOF7OggM
"""

!pip install lightgbm xgboost imbalanced-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.ensemble import IsolationForest

from imblearn.over_sampling import SMOTE

import lightgbm as lgb
import xgboost as xgb

import matplotlib.pyplot as plt

# 讀取資料
from google.colab import drive
drive.mount('/content/drive')

train_df = pd.read_csv("/content/drive/MyDrive/train_df.csv")
test_df = pd.read_csv("/content/drive/MyDrive/test_df.csv")

print("train_df shape:", train_df.shape)
print("test_df shape:", test_df.shape)

train_df.head()

print(train_df["status"].value_counts())
print(train_df["status"].value_counts(normalize=True))

y = train_df["status"]

X = train_df.drop(columns=["status"]).copy()
test_X = test_df.copy()

X = X.drop(columns=["user_id"], errors="ignore")
test_X = test_X.drop(columns=["user_id"], errors="ignore")

time_cols = [
    "confirmed_at",
    "level1_finished_at",
    "level2_finished_at",
    "twd_first_time",
    "twd_last_time",
    "crypto_first_time",
    "crypto_last_time",
    "trade_first_time",
    "trade_last_time",
    "swap_first_time",
    "swap_last_time"
]

X = X.drop(columns=time_cols, errors="ignore")
test_X = test_X.drop(columns=time_cols, errors="ignore")

for col in X.select_dtypes(include="object").columns:

    X[col] = X[col].astype("category")
    test_X[col] = test_X[col].astype("category")

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", pd.Series(y_train_res).value_counts())

lgb_model = lgb.LGBMClassifier(
    n_estimators=400,
    learning_rate=0.03,
    num_leaves=128,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgb_model.fit(X_train_res, y_train_res)

xgb_model = xgb.XGBClassifier(
    n_estimators=400,
    learning_rate=0.03,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss"
)

xgb_model.fit(X_train_res, y_train_res)

iso = IsolationForest(
    n_estimators=200,
    contamination=0.03,
    random_state=42
)

iso.fit(X_train)

lgb_prob = lgb_model.predict_proba(X_valid)[:,1]
xgb_prob = xgb_model.predict_proba(X_valid)[:,1]

iso_score = -iso.score_samples(X_valid)

risk_score = (
    0.5 * lgb_prob +
    0.3 * xgb_prob +
    0.2 * (iso_score / iso_score.max())
)

thresholds = np.arange(0.05,0.5,0.01)

records = []

for th in thresholds:

    pred = (risk_score >= th).astype(int)

    p = precision_score(y_valid,pred)
    r = recall_score(y_valid,pred)
    f1 = f1_score(y_valid,pred)

    records.append((th,p,r,f1))

threshold_df = pd.DataFrame(
    records,
    columns=["threshold","precision","recall","f1"]
)

threshold_df.sort_values("f1",ascending=False).head()

best_row = threshold_df.sort_values("f1",ascending=False).iloc[0]

best_th = best_row["threshold"]

print(best_row)

best_pred = (risk_score >= best_th).astype(int)

print(confusion_matrix(y_valid,best_pred))
print(classification_report(y_valid,best_pred))

lgb_prob_test = lgb_model.predict_proba(test_X)[:,1]
xgb_prob_test = xgb_model.predict_proba(test_X)[:,1]

iso_score_test = -iso.score_samples(test_X)

risk_test = (
    0.5 * lgb_prob_test +
    0.3 * xgb_prob_test +
    0.2 * (iso_score_test / iso_score_test.max())
)

test_pred = (risk_test >= best_th).astype(int)

submission = pd.DataFrame({
    "user_id": test_df["user_id"],
    "status": test_pred
})

submission.head()

submission.to_csv("submission.csv",index=False)

print("submission.csv saved")

"""## Colab-2

1. 讀 train_df
2. train LightGBM
3. evaluate
4. submission
"""