# -*- coding: utf-8 -*-
"""bitopro_data_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fa5H-GdRsJvOQal5pJhpyvB1ZSJ46ro-
"""

# 安裝需要的 Python 套件
# pandas：資料處理
# requests：呼叫 API
# tqdm：進度條

!pip install pandas numpy requests tqdm

# 匯入必要套件

import pandas as pd
import numpy as np
import requests

from tqdm import tqdm

# 設定 API base url
# BitoPro 的資料是透過 PostgREST API 提供

BASE_URL = "https://aws-event-api.bitopro.com"

# 這個函式會自動從 API 抓取所有資料
# 因為 API 一次只能抓固定數量，所以需要 pagination

def fetch_table(table_name, limit=1000):

    offset = 0
    all_data = []

    while True:

        url = f"{BASE_URL}/{table_name}?limit={limit}&offset={offset}"

        response = requests.get(url)
        data = response.json()

        # 如果回傳資料為空代表抓完
        if len(data) == 0:
            break

        all_data.extend(data)

        offset += limit

        print(f"{table_name} fetched rows: {offset}")

    df = pd.DataFrame(all_data)

    return df

# user_info 是所有使用者的基本資料

user_info = fetch_table("user_info")

print(user_info.shape)
user_info.head()

# 法幣出入金資料

twd_transfer = fetch_table("twd_transfer")

print(twd_transfer.shape)
twd_transfer.head()

# 虛擬幣轉帳資料

crypto_transfer = fetch_table("crypto_transfer")

print(crypto_transfer.shape)
crypto_transfer.head()

# USDT / TWD 交易

trade = fetch_table("usdt_twd_trading")

print(trade.shape)
trade.head()

# 一鍵買賣資料

swap = fetch_table("usdt_swap")

print(swap.shape)
swap.head()

# 訓練標籤與預測名單

train_label = fetch_table("train_label")
predict_label = fetch_table("predict_label")

print(train_label.shape)
print(predict_label.shape)

# 把資料存成 CSV
# 之後就不用重新抓 API

user_info.to_csv("user_info.csv", index=False)
twd_transfer.to_csv("twd_transfer.csv", index=False)
crypto_transfer.to_csv("crypto_transfer.csv", index=False)
trade.to_csv("trade.csv", index=False)
swap.to_csv("swap.csv", index=False)

train_label.to_csv("train_label.csv", index=False)
predict_label.to_csv("predict_label.csv", index=False)

# 將時間欄位轉為 datetime

twd_transfer["created_at"] = pd.to_datetime(twd_transfer["created_at"])
crypto_transfer["created_at"] = pd.to_datetime(crypto_transfer["created_at"])
trade["updated_at"] = pd.to_datetime(trade["updated_at"])
swap["created_at"] = pd.to_datetime(swap["created_at"])

# 有些金額需要乘 1e-8 才是實際值

twd_transfer["ori_samount"] = twd_transfer["ori_samount"] * 1e-8
crypto_transfer["ori_samount"] = crypto_transfer["ori_samount"] * 1e-8

# 將交易資料轉成 user-level 特徵

twd_feat = twd_transfer.groupby("user_id").agg({

    "ori_samount": ["count","sum","mean","max"]

})

twd_feat.columns = [

"twd_txn_count",
"twd_total_amount",
"twd_mean_amount",
"twd_max_amount"

]

twd_feat = twd_feat.reset_index()

twd_feat.head()

crypto_feat = crypto_transfer.groupby("user_id").agg({

    "ori_samount": ["count","sum","mean","max"]

})

crypto_feat.columns = [

"crypto_txn_count",
"crypto_total_amount",
"crypto_mean_amount",
"crypto_max_amount"

]

crypto_feat = crypto_feat.reset_index()

crypto_feat.head()

# 把所有特徵 merge 回 user_info

feature_df = user_info.copy()

feature_df = feature_df.merge(twd_feat, on="user_id", how="left")
feature_df = feature_df.merge(crypto_feat, on="user_id", how="left")

feature_df = feature_df.fillna(0)

feature_df.head()

# 建立訓練資料

train_df = feature_df.merge(train_label, on="user_id")

# 建立測試資料

test_df = feature_df.merge(predict_label, on="user_id")

print(train_df.shape)
print(test_df.shape)

from google.colab import drive
drive.mount('/content/drive')

train_df.to_csv("/content/drive/MyDrive/train_df.csv", index=False)
test_df.to_csv("/content/drive/MyDrive/test_df.csv", index=False)